### PR TITLE
feat: options类文本过长，显示优化

### PR DESCRIPTION
**Pull request by sqzhou**
### <samp>🤖 Generated by Copilot at ff56094</samp>

This pull request improves the UI layout and consistency of the result list and selection components in forms. It adds text truncation, ellipsis, and tooltips to the item elements, and fixes some flex and overflow issues. It also simplifies the class name logic using the `cx` function. The changes affect the files `_result-list.scss`, `_selection.scss`, `ResultList.tsx`, and `Selection.tsx`.

### <samp>🤖 Generated by Copilot at ff56094</samp>

> _To make the form component look nice_
> _We added some CSS and spice_
> _We used `itemRender`_
> _And `cx` to render_
> _The `title` and `ellipsis-line` slice_

### <samp>🤖 Generated by Copilot at ff56094</samp>

*  Add `ellipsis-line` class and `title` attribute to various form elements to truncate text with ellipsis and show full text on hover ([link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-e23731f1a233e56d62b653534e36c4502740ee91ea3c72d2567afa2b37812cd9L56-R63), [link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-0f0487287579e1a13ea4e8643e44936d1aaf6c272bc335585eddb6fc06126402R107), [link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-0f0487287579e1a13ea4e8643e44936d1aaf6c272bc335585eddb6fc06126402R117-R122), [link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-0f0487287579e1a13ea4e8643e44936d1aaf6c272bc335585eddb6fc06126402R419-R424), [link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-0f0487287579e1a13ea4e8643e44936d1aaf6c272bc335585eddb6fc06126402R430-R435), [link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-0f0487287579e1a13ea4e8643e44936d1aaf6c272bc335585eddb6fc06126402R446-R451), [link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-4092df2b2bdeccf1ae4a3f8ea85f4997d2090059756fce994a2f316b62ad2844L54-R67), [link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-ba63d39ad70a1c34ad20fbabdac0ec1361040e7e45d3abe4d7c7e19d6f133384L66-R80))
*  Add fixed width to result list item element and prevent result list container element from expanding beyond it ([link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-e23731f1a233e56d62b653534e36c4502740ee91ea3c72d2567afa2b37812cd9L56-R63), [link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-e23731f1a233e56d62b653534e36c4502740ee91ea3c72d2567afa2b37812cd9R86))
*  Add `overflow: hidden` property to selection item element to prevent text from overflowing ([link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-0f0487287579e1a13ea4e8643e44936d1aaf6c272bc335585eddb6fc06126402R107))
*  Import `cx` function from `classnames` module and use it to join class names in `ResultList.tsx` and `Selection.tsx` ([link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-4092df2b2bdeccf1ae4a3f8ea85f4997d2090059756fce994a2f316b62ad2844R8), [link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-4092df2b2bdeccf1ae4a3f8ea85f4997d2090059756fce994a2f316b62ad2844L54-R67), [link](https://github.com/baidu/amis/pull/7990/files?diff=unified&w=0#diff-ba63d39ad70a1c34ad20fbabdac0ec1361040e7e45d3abe4d7c7e19d6f133384L66-R80))

### CODE REVIEW

**Comment by 2betop** [comment]
className 不符合命名规范

**Comment by sqzhou** [comment]
@2betop static方法无法拿到cxd主题，所以改的时候就不加前缀了。

**Comment by 2betop** [comment]
itemRender 第二个参数，把 classnames 通过 ItemRenderStates 下发吧

**Comment by sqzhou** [comment]
好的，我修改一下

**Review by 2betop — APPROVED** [review]

**Pull request merged**
