### PR TITLE
feat: inputNubmer formatter优化

### PR DESCRIPTION
**Pull request by allenve**
### <samp>🤖 Generated by Copilot at db4ef97</samp>

Implemented and tested a `numberFormatter` function to format numbers with commas and precision. Refactored the `InputNumber` component to use the new function and improve performance and usability.

### <samp>🤖 Generated by Copilot at db4ef97</samp>

> _Sing, O Muse, of the skillful coder who devised_
> _A `numberFormatter` function, a wondrous tool_
> _That with commas and precision beautified_
> _The numeric inputs of amis, his noble rule._

### <samp>🤖 Generated by Copilot at db4ef97</samp>

*  Implement and test `numberFormatter` function in `math.ts` to format numbers with commas and precision ([link](https://github.com/baidu/amis/pull/7415/files?diff=unified&w=0#diff-e4301860018921c04669278018d4efd9880f97b910816dee541b1135b0927b1dR33-R42), [link](https://github.com/baidu/amis/pull/7415/files?diff=unified&w=0#diff-969a7c3450debd0b219e91cd7c3e39393c5091ae8ef8947e80e526c0852dd460L1-R1), [link](https://github.com/baidu/amis/pull/7415/files?diff=unified&w=0#diff-969a7c3450debd0b219e91cd7c3e39393c5091ae8ef8947e80e526c0852dd460R16-R26))
*  Replace `numberFormatter` variable in `InputNumber` component with imported function from `math.ts` and simplify string concatenation ([link](https://github.com/baidu/amis/pull/7415/files?diff=unified&w=0#diff-daae26cdbc910321ac03b9e1e11300556f4a6c5d683738f93b6d828e9fcc9685R16-R17), [link](https://github.com/baidu/amis/pull/7415/files?diff=unified&w=0#diff-daae26cdbc910321ac03b9e1e11300556f4a6c5d683738f93b6d828e9fcc9685L99-L100), [link](https://github.com/baidu/amis/pull/7415/files?diff=unified&w=0#diff-daae26cdbc910321ac03b9e1e11300556f4a6c5d683738f93b6d828e9fcc9685L400-R404))
*  Add `inputing` state property to `InputNumber` component to control when to apply formatting and avoid interfering with user input ([link](https://github.com/baidu/amis/pull/7415/files?diff=unified&w=0#diff-daae26cdbc910321ac03b9e1e11300556f4a6c5d683738f93b6d828e9fcc9685R153), [link](https://github.com/baidu/amis/pull/7415/files?diff=unified&w=0#diff-daae26cdbc910321ac03b9e1e11300556f4a6c5d683738f93b6d828e9fcc9685L166-R168), [link](https://github.com/baidu/amis/pull/7415/files?diff=unified&w=0#diff-daae26cdbc910321ac03b9e1e11300556f4a6c5d683738f93b6d828e9fcc9685L201-R203), [link](https://github.com/baidu/amis/pull/7415/files?diff=unified&w=0#diff-daae26cdbc910321ac03b9e1e11300556f4a6c5d683738f93b6d828e9fcc9685L392-R395), [link](https://github.com/baidu/amis/pull/7415/files?diff=unified&w=0#diff-daae26cdbc910321ac03b9e1e11300556f4a6c5d683738f93b6d828e9fcc9685L439-R440), [link](https://github.com/baidu/amis/pull/7415/files?diff=unified&w=0#diff-daae26cdbc910321ac03b9e1e11300556f4a6c5d683738f93b6d828e9fcc9685L448-R456))
*  Import and use `safeSub` function from `math.ts` in `InputNumber` component ([link](https://github.com/baidu/amis/pull/7415/files?diff=unified&w=0#diff-daae26cdbc910321ac03b9e1e11300556f4a6c5d683738f93b6d828e9fcc9685R16-R17))

### CODE REVIEW

**Review by 2betop — APPROVED** [review]

**Comment by Icodezhan** [comment]
@allenve 这个Merged，我拉最新的合并后的代码跑起来后，貌似千分位失效了

**Comment by Icodezhan** [comment]
> @allenve 这个Merged，我拉最新的合并后的代码跑起来后，貌似千分位失效了

我研究了一下，貌似formatter的格式化处理早于失去焦点事件blur的执行，所以当鼠标失去焦点时，inputing还是true时就执行了formatter，完了才触发了修改inputing的失去焦点事件

**Comment by Icodezhan** [comment]
说实话rc-input-number这个组件并不好用，如果可以建议换成其他的，或者自己写个

**Comment by Icodezhan** [comment]
@allenve

**Comment by allenve** [comment]
rc-input-number 缓存 formatter 了，目前看不太好处理，先回滚了

**Comment by Icodezhan** [comment]
> rc-input-number 缓存 formatter 了，目前看不太好处理，先回滚了

换一种思路，在formatter不用控制当前是不输入态（inputing）直接按精度格式化，只是会出现我想输入的实际是123456，但在我输入的过程中输入123456的1时变成了1.00，但是通过change事件去改变光标的位置，例如我输入123456的1时虽然变成了1.00，但光标依旧在1后边而不是在1.00后边，
可以参考react-number-format这个组件的处理：https://codesandbox.io/s/keen-field-26ub7?file=/src/App.js
这样子才是合理的
（还是得吐槽一下rc-input-number确实不好用）

**Comment by Icodezhan** [comment]
> rc-input-number 缓存 formatter 了，目前看不太好处理，先回滚了

如果可以建议使用react-number-format出个新的数字框组件，这个是真的好用

**Comment by allenve** [comment]
我们内部评估一下哈

**Comment by Icodezhan** [comment]
> 我们内部评估一下哈

对于保险、财务系统，这种涉及大量金额录入的，肯定是需要保留小数点精度以及千分位，而这一点rc-input-number做的并不好。

建议使用react-number-format弄个【数字格式化输入框】组件

**Pull request merged**
