### PR TITLE
chore: jssdk 中使用代码编辑器在不同的 locale 下加载编辑器对应的语言文件 Close: #8880

### PR DESCRIPTION
**Pull request by 2betop**
### Why

Close: #8880

### CODE REVIEW

**Review by lurunze1226 — APPROVED** [review]

**Review by nwind — APPROVED** [review]

**Comment by MatsiukMykola** [comment]
Please Update Monaco Editor to Last Version and add sample to add custom highlight.

**Comment by 2betop** [comment]
I'm afraid We can't do this because the new version of Monaco Editor has browser compatibility issues.

**Comment by MatsiukMykola** [comment]
are possible to add a custom syntax highlight?
i will add Jinja (Python Django Template) syntax, but don't understand how this do from amis

**Comment by 2betop** [comment]
Please try this. https://aisuda.bce.baidu.com/amis/zh-CN/components/form/editor#%E7%BC%96%E8%BE%91%E5%99%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%80%E5%8F%91

**Pull request merged**
